name = "OneOne"
author = "woldann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3508e0a07336e5c7563ead6e1163e386173a7d0d59b32b925d1caf6d4977c35"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
