name = "OneOne"
author = "woldann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9994d2e39485c31b1700da5750456fc14b972730c95e19fd0ce2bc96f44e0b9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
